name: Node.js CI

on:
  push:
    branches: [test-branch-1]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Delete node_modules
        run: rm -rf node_modules

      - name: Install env-cmd
        run: npm install -g env-cmd

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
