name: Node.js CI

on:
  push:
    branches: [ test-branch-1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: --name mongodb-test

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Delete node_modules
        run: rm -rf node_modules

      - name: Install env-cmd
        run: npm install -g env-cmd

      - name: Dotenv Action
        uses: falti/dotenv-action@v1.0.4
        with:
          path: ./.env.test

      - run: npm install

      - run: npm test
